[project]
name = "share-note-gcp-api"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "fastapi>=0.129.0",
    "uvicorn>=0.41.0",
    "google-cloud-firestore>=2.23.0",
    "pydantic>=2.12.5",
]
